"""
utils.py - Export utilities: produces CSV bytes and SQL INSERT statements
           from a dict of {table_name: pd.DataFrame}.
"""

import io
from datetime import date, datetime

import pandas as pd


# ---------------------------------------------------------------------------
# CSV export
# ---------------------------------------------------------------------------

def dataframes_to_csv_zip(dataframes: dict[str, pd.DataFrame]) -> bytes:
    """
    Return an in-memory ZIP archive where each table becomes <table>.csv.
    """
    import zipfile

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        for table_name, df in dataframes.items():
            csv_bytes = df.to_csv(index=False).encode("utf-8")
            zf.writestr(f"{table_name}.csv", csv_bytes)
    buf.seek(0)
    return buf.read()


def dataframe_to_csv_bytes(df: pd.DataFrame) -> bytes:
    return df.to_csv(index=False).encode("utf-8")


# ---------------------------------------------------------------------------
# SQL INSERT export
# ---------------------------------------------------------------------------

def dataframes_to_sql_inserts(
    dataframes: dict[str, pd.DataFrame],
    batch_size: int = 500,
) -> str:
    """
    Convert all DataFrames to SQL INSERT statements (MySQL / PostgreSQL
    compatible dialect).  Values are properly escaped.
    """
    parts: list[str] = []
    parts.append("-- Generated by Syngen – Synthetic Data Generator")
    parts.append("-- https://github.com/syngen\n")

    for table_name, df in dataframes.items():
        if df.empty:
            continue

        parts.append(f"-- Table: {table_name}")
        columns = ", ".join(f"`{c}`" for c in df.columns)

        # Split into batches for readability / performance
        for start in range(0, len(df), batch_size):
            chunk = df.iloc[start : start + batch_size]
            value_rows: list[str] = []

            for _, row in chunk.iterrows():
                vals = ", ".join(_sql_value(v) for v in row)
                value_rows.append(f"  ({vals})")

            values_str = ",\n".join(value_rows)
            parts.append(
                f"INSERT INTO `{table_name}` ({columns}) VALUES\n{values_str};"
            )

        parts.append("")  # blank line between tables

    return "\n".join(parts)


def _sql_value(v) -> str:
    """Convert a Python value to its SQL literal representation."""
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, datetime):
        return f"'{v.strftime('%Y-%m-%d %H:%M:%S')}'"
    if isinstance(v, date):
        return f"'{v.strftime('%Y-%m-%d')}'"
    # Escape single quotes in strings
    escaped = str(v).replace("'", "''")
    return f"'{escaped}'"


# ---------------------------------------------------------------------------
# Session helpers
# ---------------------------------------------------------------------------

def validate_session(
    session_id: str,
    schema_store: dict,
    data_store: dict,
    *,
    require_data: bool = False,
) -> None:
    """Raise ValueError if the session is unknown or data is missing."""
    if session_id not in schema_store:
        raise ValueError(f"Session '{session_id}' not found. Upload a schema first.")
    if require_data and session_id not in data_store:
        raise ValueError(
            f"No data generated for session '{session_id}'. "
            "Call /generate-data first."
        )
